<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-SAHP40V1" failures="3" tests="3" name="Test(failed)" time="13.234" errors="0" timestamp="2022-08-02T08:58:03 IST">
  <testcase classname="package18.DataProvider1" name="LoginMethod" time="2.86">
    <failure type="java.lang.AssertionError" message="expected [nopCommerce demo store] but found [nopCommerce demo store. Login]">
      <![CDATA[java.lang.AssertionError: expected [nopCommerce demo store] but found [nopCommerce demo store. Login]
at package18.DataProvider1.LoginMethod(DataProvider1.java:36)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- LoginMethod -->
  <testcase classname="package18.DataProvider1" name="LoginMethod" time="1.457">
    <failure type="java.lang.AssertionError" message="expected [nopCommerce demo store] but found [nopCommerce demo store. Login]">
      <![CDATA[java.lang.AssertionError: expected [nopCommerce demo store] but found [nopCommerce demo store. Login]
at package18.DataProvider1.LoginMethod(DataProvider1.java:36)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- LoginMethod -->
  <testcase classname="package18.DataProvider1" name="LoginMethod" time="1.32">
    <failure type="java.lang.AssertionError" message="expected [nopCommerce demo store] but found [nopCommerce demo store. Login]">
      <![CDATA[java.lang.AssertionError: expected [nopCommerce demo store] but found [nopCommerce demo store. Login]
at package18.DataProvider1.LoginMethod(DataProvider1.java:36)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- LoginMethod -->
</testsuite> <!-- Test(failed) -->
